[web]
web01 ansible_host=192.168.10.20

[dns]
dns01 ansible_host=192.168.10.21

[sftp]
srv01 ansible_host=192.168.10.22

[database]
db01 ansible_host=192.168.10.23

[monitoring]
mon01 ansible_host=192.168.10.24

[all:vars]
ansible_user=admin
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new -o ProxyJump=root@192.168.1.150'
